### ISSUE TITLE
Redisplay task on the canonical link

### ISSUE THREAD

**Issue by jgmac1106** [mapkyca/review-courseware#6]
Each task has it's own url. Going to be great come time for webmention badging. Just make sure to re-display the text of the task on the page.

**Comment by mapkyca** [comment]
Not sure what you mean, could you explain and maybe give some examples?

**Comment by jgmac1106** [comment]
yes, when you click on the link to the task you only get a comment box. On the module page the task has some copy. I want to include the copy so you see it if you click on the link to the task

**Comment by mapkyca** [comment]
Ahh... events plugin wasn't switched on. Try again now...
